<a href="https://colab.research.google.com/github/Md-Kashif/DSFEB12/blob/main/Python_Day_1_Feb_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print ("My name is mohammed Kashif")

My name is mohammed Kashif


In [2]:
 # COMMENTS START WITH A HASH
 # ENTER - IT TO TEH NEXT LINE IN HTE SAME CODE BLOCK
 # SHIFT + ETER - EXECUTED THE CURRENT CODE BLOCK AND GOES TO THE NEXT CODE BLOCK
 # ALT + ENTER - IT ECUTED ONLY THE PARTICULAR CODE BLOCK AND CREARTES A NEW CODE BLOCK
 # COMMAND + ENTER - EXECUTES TEH PARTICLUARBLOCK OF CODE

In [3]:
# TYPES OF BRACKETS
# [] - DATA EXTRACTION / SLICING OF DATA, LISTS
# {} - DICTIONARIES / SETS
# () - METHODS/ FINCTIONS, TUPLES

In [4]:
# ----- VARIABLES AND DATA TYPES -----

In [5]:
x = 20
x 

20

In [6]:
type (x)

int

In [7]:
y = "Kashif"
y

'Kashif'

In [8]:
type (y)

str

In [9]:
z = 13.5
type (z)

float

In [10]:
a = True
type (a)

bool

In [11]:
a = 20
b = 10
sum = a + b
print (sum)

30


In [12]:
a = 100
b = 80
diff = a - b
print (diff)

20


In [13]:
a = 990
b = 99
print (990/99)

10.0


In [14]:
a = 85
b = 10
print (a * b)

850


In [15]:
print(20 + 10)
print(100 - 80)
print(990 / 99)
print(85 * 10)

30
20
10.0
850


In [16]:
list1 = ["Kashif", 22, 33.5, True]

In [17]:
list1

['Kashif', 22, 33.5, True]

In [18]:
#indexing in python starts with 0

In [19]:
list1[1]

22

In [20]:
list1[1] = 23
list1

['Kashif', 23, 33.5, True]

In [21]:
a = "Good Morning"

In [22]:
b = "Kashif"

In [23]:
a+b

'Good MorningKashif'

In [24]:
a + " " + b

'Good Morning Kashif'

In [25]:
7 > 5

True

In [26]:
20<18

False

In [27]:
8  == 7

False

In [28]:
8 !=710 

True

In [29]:
10 <=20

True

In [30]:
20 >= 30

False

In [31]:
test = 4 > 1

In [32]:
test

True

In [33]:
type (test)

bool

In [34]:
test2 = not (5 > 1)

In [35]:
test2 

False

In [36]:
test or test2

True

In [37]:
sample1 = 7 > 6

In [38]:
sample2 = 6 > 8

In [39]:
sample1 and sample2 

False

In [40]:
sample3 = 5 > 1

In [41]:
smaple4 = 6 >3

In [42]:
sample3 and smaple4

True

In [43]:
i = 0
while i <= 10:
  print(i)
  i = i+1
print ("Python is cool") # if this was in the loop it would be executed along wiht the conditiion 

0
1
2
3
4
5
6
7
8
9
10
Python is cool


In [44]:
range (6)

range(0, 6)

In [45]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [46]:
# indexing starts from o and ads with last -1

In [47]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [48]:
for i in range (6):
  print(i)
  print("Today is a good day!")

0
Today is a good day!
1
Today is a good day!
2
Today is a good day!
3
Today is a good day!
4
Today is a good day!
5
Today is a good day!


In [49]:
import numpy as np
from numpy.random import randn

In [50]:
result = None 
if x > 1:
  result = "Greater than 1"
print(x)
print(result)

20
Greater than 1


In [51]:
result = None
x = randn()
if x > 1:
  result = "Greater than 1"
elif x < -1:
  result = "Less than -1"
else:
  result = "Between -1 and 1"
print(x)
print(result)

-0.6571617096220517
Between -1 and 1


In [52]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [53]:
type(list1)

list

In [54]:
list(range(1, 51, 3))

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [57]:
list2 = list(range(1, 51, 3))

In [59]:
list2[1]

4

In [62]:
print(list2[1])

4


In [63]:
letters = ['A', 'B', "C", "D", "E", "F", "G", "H", "I", "J"]

In [64]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [71]:
letters[1:8:2] # index -1 so uptil index 7

['B', 'D', 'F', 'H']

In [72]:
letters[-9: -1: 2] # 2 means every second letter

['B', 'D', 'F', 'H']

In [67]:
letters[1::2]

['B', 'D', 'F', 'H', 'J']

In [68]:
letters[::3]

['A', 'D', 'G', 'J']

In [69]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [70]:
letters[7:]

['H', 'I', 'J']

In [73]:
letters [::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [74]:
letters[1:6:-1] # since the order of the list is reversed 1 : 6 index will not work here 

[]

In [75]:
letters [6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [76]:
tuple1 = (12, 36, 72)

In [77]:
tuple1[1]

36

In [78]:
tuple1[1] = 48

TypeError: ignored

In [79]:
list3 = [12, 36, 73]

In [80]:
list3[1] = 42

In [82]:
list3

[12, 42, 73]

In [83]:
len(list3)

3

In [84]:
list(range(1, 65, 3))

[1,
 4,
 7,
 10,
 13,
 16,
 19,
 22,
 25,
 28,
 31,
 34,
 37,
 40,
 43,
 46,
 49,
 52,
 55,
 58,
 61,
 64]

In [85]:
list4 = list(range(1, 65, 3))

In [87]:
len(list4)

22

In [88]:
max(list4)

64

In [89]:
min(list4)

1

In [90]:
import numpy as np

In [91]:
list5 = ['A', 20, 36.5, True]

In [92]:
np.array(list5)

array(['A', '20', '36.5', 'True'], dtype='<U32')

In [95]:
list6 = [20, 30.5, True]

In [96]:
np.array(list6)

array([20. , 30.5,  1. ])

In [100]:
list7 = [20, True]

In [99]:
np.array(list7)

array([20, 30,  1])

In [101]:
list8 = [True]

In [102]:
np.array(list8)

array([ True])

In [103]:
b = np.array([2345, 6789, 9876, 1456, -1234])

In [104]:
b.mean()

3846.4

In [105]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [106]:
b[::2]

array([ 2345,  9876, -1234])

In [107]:
b[1::2]

array([6789, 1456])

In [110]:
c = b[2:4] # uptil 4 but not incuding 4

In [109]:
c

array([9876, 1456])

In [111]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [112]:
dict1 = {'Index0' : 'Emp No.', 'Index1' : 'EmoName', 'Index2' : 'Salary'}

In [113]:
dict1['Index2']

'Salary'